website/discord/urls.py
from django.urls import path
from . import views
app_name = "discord"

urlpatterns = [
    # Main application URLs
    path('', views.home,  name="home"),                  # URL for home page
    path('room/<str:pk>/', views.room, name="room"),     # URL for individual room page
    path('profile/', views.userProfile, name="user-profile"),  # URL for user profile page

    # Authentication URLs
    path('login/', views.loginPage, name="login"),       # URL for login page
    path('logout/', views.logoutUser, name="logout"),    # URL for logout page
    path('register/', views.registerPage, name="register"),  # URL for registration page

    # Room management URLs
    path('create-room/', views.createRoom, name="create-room"),  # URL for creating a new room
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),

   # User profile management URL
    path('update-user/', views.updateUser, name="update-user"),  # URL for updating user profile

    # Other URLs
    path('topics/', views.topicsPage, name="topics"),    # URL for displaying topics
    path('activity/', views.activityPage, name="activity"),  # URL for displaying activity
]

website/web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('discord.urls', namespace='discord')),
    path('auth/', include('allauth.urls')),
]

urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

website/discord/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    profile_picture = models.ImageField(upload_to='profiles',default='name.png')





# Model representing a topic for chat rooms
class Topic(models.Model):
    name = models.CharField(max_length=200)  # Name of the topic

    def __str__(self):
        # Return the name of the topic when converted to a string
        return self.name  # Return the name of the topic when converted to a string


# Model representing a chat room
class Room(models.Model):
    # CustomUser who created the room
    host = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    # Topic of the room
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    # Name of the room
    name = models.CharField(max_length=200)
    # Description of the room
    description = models.TextField(null=True, blank=True)
    # CustomUsers participating in the room
    participants = models.ManyToManyField(CustomUser, related_name='participants')
    # Date and time when the room was last updated
    updated = models.DateTimeField(auto_now=True)
    # Date and time when the room was created
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Ordering of instances by 'updated' and 'created' fields
        ordering = ['-updated', '-created']

    def __str__(self):
        # Return the name of the room when converted to a string
        return self.name


# Model representing a message in a chat room
class Message(models.Model):
    # CustomUser who sent the message
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    # Room in which the message was sent
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    # Content of the message
    body = models.TextField()
    # Date and time when the message was last updated
    updated = models.DateTimeField(auto_now=True)
    # Date and time when the message was created
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Ordering of instances by 'updated' and 'created' fields
        ordering = ['-updated', '-created']

    def __str__(self):
        # Return the first 50 characters of the message body when converted to a string
        return self.body[0:50]

website/discord/forms.py
from django.forms import ModelForm
from .models import Room
# from django.contrib.auth.models import User
from discord.models import CustomUser

# Form for creating or updating a Room model instance
class RoomForm(ModelForm):
    class Meta:
         # Specify the model the form is associated with
        model = Room
        # Include all fields of the Room model in the form
        fields = '__all__'
        # Exclude 'host' and 'participants' fields from the form
        exclude = ['host', 'participants']

# Form for updating User model instance
class UserForm(ModelForm):
    class Meta:
        # Specify the model the form is associated with
        model = CustomUser
        # Include only 'username' and 'email' fields in the form
        fields = ['profile_picture','username', 'email']

website/discord/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from .models import Room, Topic, Message, CustomUser
from .forms import RoomForm, UserForm

# Create your views here.

# Define the view for the login page
def loginPage(request):
    # Set the current page to 'login'
    page = 'login'

    # If the user is already authenticated, redirect them to the home page
    if request.user.is_authenticated:
        return redirect('discord:home')

    # If the request method is POST (i.e., form submission)
    if request.method == 'POST':
        # Retrieve the username and password from the form data
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Attempt to find a user with the given username
        try:
            user = CustomUser.objects.get(username=username)
        # If the user does not exist, display an error message
        except CustomUser.DoesNotExist:
            messages.error(request, 'CustomUser does not exist')

        # Authenticate the user using the provided credentials
        user = authenticate(request, username=username, password=password)

        # If authentication is successful, log the user in and redirect to the home page
        if user is not None:
            login(request, user)
            return redirect('discord:home')
        # If authentication fails, display an error message
        else:
            messages.error(request, 'CustomUsername OR password does not exist')

    # Prepare the context to be passed to the template
    context = {'page': page}

    # Render the login/register template with the provided context
    return render(request, 'discord/login_register.html', context)

# Define the view for logging out a user
def logoutUser(request):
    # Log out the current user
    logout(request)
    # Redirect the user to the home page
    return redirect('discord:home')


# Define the view for the registration page
def registerPage(request):
    # Create an instance of UserCreationForm
    form = UserCreationForm()
    
    # If the request method is POST (i.e., form submission)
    if request.method == 'POST':
        # Bind the form with the POST data
        form = UserCreationForm(request.POST)
        # Check if the form data is valid
        if form.is_valid():
            # Save the form data to create a new user, without committing to the database yet
            user = form.save(commit=False)
            # Convert the username to lowercase
            user.username = user.username.lower()
            # Save the user to the database
            user.save()
            # Log in the newly registered user
            login(request, user)
            # Redirect the user to the home page
            return redirect('discord:home')
        else:
            # If form validation fails, display an error message
            messages.error(request, 'An error occurred during registration')

    # Render the login/register template with the form (whether it's empty or bound with data)
    return render(request, 'discord/login_register.html', {'form': form})

# Define the view for the home page
def home(request):
    # Get the value of 'q' from the query parameters, defaulting to an empty string if not present
    q = request.GET.get('q') if request.GET.get('q') is not None else ''

    # Filter rooms based on search query
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |  # Filter rooms by topic name containing the search query
        Q(name__icontains=q) |          # Filter rooms by name containing the search query
        Q(description__icontains=q)     # Filter rooms by description containing the search query
    )

    # Retrieve the first 5 topics
    topics = Topic.objects.all()[0:5]

    # Count the number of filtered rooms
    room_count = rooms.count()

    # Filter messages based on the search query
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))

    # Prepare the context to be passed to the template
    context = {
        'rooms': rooms,                 # Filtered rooms
        'topics': topics,               # First 5 topics
        'room_count': room_count,       # Number of filtered rooms
        'room_messages': room_messages  # Filtered messages
    }

    # Render the home template with the provided context
    return render(request, 'discord/home.html', context)

# Define the view for a specific chat room
def room(request, pk):
    # Retrieve the room object with the specified primary key (pk)
    room = Room.objects.get(id=pk)
    
    # Retrieve all messages associated with the room
    room_messages = room.message_set.all()
    
    # Retrieve all participants in the room
    participants = room.participants.all()

    # If the request method is POST (i.e., form submission)
    if request.method == 'POST':
        # Create a new message object with the submitted data
        message = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        # Add the current user to the participants of the room
        room.participants.add(request.user) 
        # Redirect the user back to the current room page
        return redirect('discord:room', pk=room.id)

    # Prepare the context to be passed to the template
    context = {
        'room': room,                         # The current room
        'room_messages': room_messages,       # Messages in the current room
        'participants': participants          # Participants in the current room
    }

    # Render the room template with the provided context
    return render(request, 'discord/room.html', context)

# Define the view for a user's profile
def userProfile(request):
    # Retrieve the user object with the specified primary key (pk)
    # user = CustomUser.objects.get(id=pk)
    user = request.user
    
    # Retrieve all rooms associated with the user
    rooms = user.room_set.all()
    
    # Retrieve all messages sent by the user
    room_messages = user.message_set.all()
    
    # Retrieve all topics
    topics = Topic.objects.all()

    # Prepare the context to be passed to the template
    context = {
        'user': user,                   # The current user
        'rooms': rooms,                 # Rooms associated with the user
        'room_messages': room_messages, # Messages sent by the user
        'topics': topics                # All topics
    }
    
    # Render the profile template with the provided context
    return render(request, 'discord/profile.html', context)


# Define the view for creating a room
@login_required(login_url='discord:login')  # Ensure that the user is logged in before accessing this view
def createRoom(request):
    # Create an instance of RoomForm
    form = RoomForm()
    
    # Retrieve all topics
    topics = Topic.objects.all()
    
    # If the request method is POST (i.e., form submission)
    if request.method == 'POST':
        # Retrieve the topic name from the form data
        topic_name = request.POST.get('topic')
        # Get or create a topic object with the retrieved name
        topic, created = Topic.objects.get_or_create(name=topic_name)

        # Create a new room object with the submitted data
        Room.objects.create(
            host=request.user,                          # The user creating the room
            topic=topic,                                # The topic associated with the room
            name=request.POST.get('name'),              # The name of the room
            description=request.POST.get('description') # The description of the room
        )
        
        # Redirect the user to the home page after creating the room
        return redirect('discord:home')

    # Prepare the context to be passed to the template
    context = {
        'form': form,     # Room creation form
        'topics': topics  # All topics
    }
    
    # Render the room creation form template with the provided context
    return render(request, 'discord/room_form.html', context)

# View for updating a room
@login_required(login_url='discord:login')  # Ensure that the user is logged in before accessing this view
def updateRoom(request, pk):
    # Retrieve the room object with the specified primary key (pk)
    room = Room.objects.get(id=pk)
    
    # Create a form instance for updating the room with existing data
    form = RoomForm(instance=room)
    
    # Retrieve all topics
    topics = Topic.objects.all()

    # Check if the current user is the host of the room
    if request.user != room.host:
        return HttpResponse('You are not allowed here!!!')

    # If the request method is POST (i.e., form submission)
    if request.method == 'POST':
        # Retrieve the topic name from the form data
        topic_name = request.POST.get('topic')
        # Get or create a topic object with the retrieved name
        topic, created = Topic.objects.get_or_create(name=topic_name)
        # Update the room object with the submitted data
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        # Redirect the user to the home page after updating the room
        return redirect('discord:home')

    # Prepare the context to be passed to the template
    context = {'form': form, 'topics': topics, 'room': room}
    
    # Render the room update form template with the provided context
    return render(request, 'discord/room_form.html', context)

# View for deleting a room
@login_required(login_url='discord:login')  # Ensure that the user is logged in before accessing this view

website/discord/templates/discord/activity_component.html
{% load static %}
<div class="activities">
   <div class="activities__header">
       <h2>Recent Activities</h2>
   </div>
   {% for message in room_messages %}
   <div class="activities__box">
       <div class="activities__boxHeader roomListRoom__header">
           <a href="{% url 'discord:user-profile' %}" class="roomListRoom__author">
               <div class="avatar avatar--small">
                   <img src="{% static 'images/avatar.svg' %}" />
               </div>
               <p>
                   @{{message.user.username}}
                   <span>{{message.created|timesince}} ago</span>
               </p>
           </a>

           {% if request.user == message.user %}
           <div class="roomListRoom__actions">
               <a href="{% url 'discord:delete-message' message.id %}">
                   <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                       <title>remove</title>
                       <path
                           d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                       </path>
                   </svg>
               </a>
           </div>
           {% endif %}
       </div>
       <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'discord:room' message.room.id %}">{{message.room}}</a>”</p>
            <div class="activities__boxRoomContent">{{message.body}}</div>
       </div>
   </div>
   {% endfor %}
</div>

website/discord/templates/discord/feed_component.html
{% for room in rooms %}
{% load static %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'discord:user-profile' %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{% static 'images/avatar.svg' %}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'discord:room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'discord:room' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>
{% endfor %}

website/discord/templates/discord/home.html
{% extends 'main.html' %}

{% block content %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
        {% include 'discord/topics_component.html' %}
        <!-- Topics End -->




        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form action="{% url 'discord:home' %}" method="get" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'discord:topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'discord:activity' %}">Recent Activities</a>
            </div>
          </div>

          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{room_count}} Rooms available</p>
            </div>
            <a class="btn btn--main" href="{% url 'discord:create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>

    
          {% include 'discord/feed_component.html' %}
    
        </div>

        <!-- Room List End -->

        <!-- Activities Start -->
        {% include 'discord/activity_component.html' %}
        <!-- Activities End -->
      </div>
    </main>

{% endblock %}

website/discord/templates/discord/login_register.html
{% extends 'main.html' %}

{% block content %}
    <main class="auth layout">

      {% if page == 'discord:login' %}
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Login</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>

            <form class="form" action="" method="post">
              {% csrf_token %}
              <div class="form__group form__group">
                <label for="room_name">Username</label>
                <input id="username" name="username" type="text" placeholder="e.g. dennis_ivy" />
              </div>
              <div class="form__group">
                <label for="password">Password</label>
                <input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                />
              </div>

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32"
                >
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path>
                </svg>

                Login
              </button>
            </form>

            <div class="auth__action">
                <p>Haven't signed up yet?</p>
                <a href="{% url 'discord:register' %}" class="btn btn--link">Sign Up</a>
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <div class="container">
          <div class="layout__box">
            <div class="layout__boxHeader">
              <div class="layout__boxTitle">
                <h3>Register</h3>
              </div>
            </div>
            <div class="layout__body">
              <h2 class="auth__tagline">Find your study partner</h2>
  
              <form class="form" action="" method="post">
                {% csrf_token %}
                
                {% for field in form %}
                <div class="form__group form__group">
                  <label for="room_name">{{field.label}}</label>
                  {{field}}
                </div>
                {% endfor %}
  
                <button class="btn btn--main" type="submit">
                  <svg
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewBox="0 0 32 32"
                  >
                    <title>lock</title>
                    <path
                      d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                    ></path>
                    <path
                      d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                    ></path>
                  </svg>
  
                  Register
                </button>
              </form>
  
              <div class="auth__action">
                <p>Already signed up yet?</p>
                <a href="{% url 'discord:login' %}" class="btn btn--link">Sign Up</a>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
      </main>
      {% endblock %}

website/discord/templates/discord/room.html
{% extends 'main.html' %}

{% block content %}
<main class="profile-page layout layout--2">
  <div class="container">
    <!-- Room Start -->
    <div class="room">
      <div class="room__top">
        <div class="room__topLeft">
          <a href="{% url 'discord:home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Study Room</h3>
        </div>
        {% if room.host == request.user %}
        <div class="room__topRight">
          <a href="{% url 'discord:update-room' room.id %}">
            <svg enable-background="new 0 0 24 24" height="32" viewBox="0 0 24 24" width="32"
              xmlns="http://www.w3.org/2000/svg">
              <title>edit</title>
              <g>
                <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
              </g>
              <g>
                <g>
                  <path
                    d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z" />
                </g>
                <g>
                  <path
                    d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z" />
                </g>
              </g>
            </svg>
          </a>
          <a href="{% url 'discord:delete-room' room.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
              </path>
            </svg>
          </a>
        </div>
        {% endif %}

      </div>
      <div class="room__box scroll">
        <div class="room__header scroll">
          <div class="room__info">
            <h3>{{room.name}}</h3>
            <span>{{room.created|timesince}} ago</span>
          </div>
          <div class="room__hosted">
            <p>Hosted By</p>
            <a href="{% url 'discord:user-profile' %}" class="room__author">
              <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
              </div>
              <span>@{{room.host.username}}</span>
            </a>
          </div>
          <!-- <div class="room__details">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, tenetur laudantium? Dicta repellendus
            rerum consectetur, voluptatem repudiandae eum ea porro cupiditate provident nulla, deserunt, ab ipsum
            corporis laboriosam deleniti molestias?
          </div> -->
          <span class="room__topics">{{room.topic}}</span>
        </div>

        <div class="room__conversation">
          <div class="threads scroll">


            {% for message in room_messages %}
            <div class="thread">
              <div class="thread__top">
                <div class="thread__author">
                  <a href="{% url 'discord:user-profile'%}" class="thread__authorInfo">
                    <div class="avatar avatar--small">
                      <img src="{{message.user.avatar.url}}" />
                    </div>
                    <span>@{{message.user.username}}</span>
                  </a>
                  <span class="thread__date">{{message.created|timesince}} ago</span>
                </div>

                {% if request.user == message.user %}
                <a href="{% url 'discord:delete-message' message.id %}">
                  <div class="thread__delete">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                      </path>
                    </svg>
                  </div>
                </a>
                {% endif %}
              </div>
              <div class="thread__details">
                {{message.body}}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>

      </div>
      <div class="room__message">
        <form action="" method="POST">
          {% csrf_token %}
          <input name="body" placeholder="Write your message here..." />
        </form>
      </div>
    </div>
    <!-- Room End -->

    <!--   Start -->
    <div class="participants">
      <h3 class="participants__top">Participants <span>({{participants.count}} Joined)</span></h3>
      <div class="participants__list scroll">
        {% for user in participants %}
        <a href="{%  url 'discord:user-profile' %}" class="participant">
          <div class="avatar avatar--medium">
            <img src="{{user.avatar.url}}" />
          </div>
          <p>
            {{user.name}}
            <span>@{{user.username}}</span>
          </p>
        </a>
        {% endfor %}
      </div>
    </div>
    <!--  End -->
  </div>
</main>
<script src="script.js"></script>
{% endblock content %}